### ISSUE TITLE
Pages deploy is not gated on CI: main deploys to production even when its CI run fails or is cancelled

### ISSUE THREAD

**Issue by pcowhill** [pcowhill/claude-agile-team-demo#91]
## Problem

`docs/rules/quality-and-ci.md` states the deployment principle: **"CI protects production: deployment happens after checks pass."** The actual `deploy.yml` does not implement it. The deploy workflow triggers directly on every push to `main`, runs only `npm ci && npm run build`, and deploys — it runs no lint, no typecheck, no tests, and has no dependency on the `CI` workflow's outcome.

This is not hypothetical; the gap was exercised repeatedly during the #85 apt-hang era:

- Main CI runs 60 (`8f91e0f`, the #78 merge), 62 (`1db7673`, #80), 66 (`a954a17`, #81) and 70 (`f4ce6a9`, #84) all ended **cancelled** (killed by the 20-minute job timeout while the e2e job hung) — and the corresponding "Deploy to GitHub Pages" runs 29, 30, 31 and 34 each completed **success**, shipping to production with no test evidence from main.
- Main CI run 74 attempt 1 (`bfe7375`, the #87 merge) ended in an honest **failure** (#89); Deploy run 36 succeeded anyway.

In every one of these cases the deployed content happened to be fine — each PR's own CI was green on its merge ref before merging. But that is the situation the gate exists for anyway: the realistic hazard is a **semantic conflict between two independently-green PRs** merged close together (this period saw four merges to main inside three hours, and up to three parallel implementation PRs are now allowed by #55/#59). If that ever produces a main whose tests fail, today's pipeline deploys it to the customer regardless.

## Desired outcome

A push to `main` reaches GitHub Pages only after main's checks pass, restoring the documented principle. Reasonable shapes (implementer's choice):

- **Gate on the CI workflow:** trigger the deploy via `workflow_run` on the `CI` workflow's completion and deploy only on `conclusion == 'success'`; or
- **Self-contained gate:** run the same checks (lint, typecheck, unit tests — the e2e job being optional here is a judgment call given its infra flakiness history, #85/#86/#89/#90) inside `deploy.yml` before the deploy job.

Tradeoff worth an explicit decision in the PR: gating on the full CI workflow couples deployment latency and availability to the e2e job (the flakiest part historically, though #90 bounded it to ~10 minutes worst case); a lint+typecheck+unit gate inside `deploy.yml` is faster and immune to that flake but duplicates check definitions. Either satisfies this issue.

## Acceptance criteria

1. A `main` push whose gating checks fail (or are cancelled) does not deploy to Pages; a push whose gating checks pass deploys as today.
2. The chosen gating shape and its tradeoff (full-CI vs. subset) are stated in the PR description.
3. The happy path is evidenced by the first post-merge push to `main` deploying successfully with the new workflow (and the workflow YAML validating in the PR's own CI).
4. `docs/rules/quality-and-ci.md` needs no change if the full-CI gate is chosen; if a subset gate is chosen, the deployment section gains one sentence saying which checks gate the deploy.

## Related

- Found during the 2026-08-20 retrospective (see `docs/retrospectives/2026-08-20.md` once merged).
- Context: #85 / #86 / #89 / #90 (the CI hang that exposed the gap), #55 / #59 (parallel PRs increase the semantic-conflict window).

**Comment by pcowhill** [comment]
Implementation starting in this session, on branch `claude/go-nbp1j5` (harness-assigned; it exists on origin with no open PR — leftover state, safe to reuse per `docs/rules/development.md`).

Chosen shape: **gate on the full CI workflow** via `workflow_run` — single definition of the checks, no duplication in `deploy.yml`; the latency/flake coupling to the e2e job is acceptable now that #86/#90 bound its worst case, and a failed CI can simply be re-run to trigger the deploy. Tradeoff will be restated in the PR per acceptance criterion 2; criterion 4 then requires no docs change.

---
_Generated by [Claude Code](https://claude.ai/code)_
